package com.oac.query.strategy;

/** 框架设计方案中定义的物理执行策略。 */
public enum SplitStrategy {
    SINGLE_SOURCE_SINGLE_TABLE,
    SINGLE_SOURCE_MULTI_TABLE_JOIN,
    CROSS_SOURCE_MEMORY_MERGE,
    DAG_DEPENDENT_QUERY,
    ASSOCIATION_GRAPH_PUSHDOWN,
    ASSOCIATION_RELATIONAL_JOIN,
    ASSOCIATION_MULTI_STAGE_ASSEMBLE,
    AGGREGATE_PUSHDOWN,
    AGGREGATE_PARTIAL_PUSHDOWN_MERGE,
    AGGREGATE_MEMORY,
    DAG_DEPENDENT_AGGREGATE
}
